# Generated by Django 3.2 on 2021-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210419_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myapp.Tag', verbose_name='Тэги'),
        ),
    ]
