# Generated by Django 3.2 on 2021-04-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_answer_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('user', 'question')},
        ),
    ]
